### ISSUE TITLE
An idea for linking github homebrew

### ISSUE THREAD

**Issue by ksanislo** [TurtleP/Flask#1]
You can fairly easily use the github API to pull the latest stable (or selectively unstable) .cia release files knowing only the author and project name. That would probably be a better choice than having the cia URL pre-defined in a text file.

There's a good python example of this in the [reddit QR bot](https://github.com/thesouldemon/3DS-QR-Poster/blob/master/post_qr.py), and [Hamcha's lumaupdate](https://github.com/Hamcha/lumaupdate) also does something similar in C++ on the 3DS itself too.

Also, the QR bot has some examples of using the Range: HTTP header to grab specific parts of the SMDH data and titleID from the CIA without downloading it first. Combined with some sqlite based caching, you can probably avoid needing to keep a full list of the data for what is available.

**Comment by TurtleP** [comment]
Perhaps. I definitely could use that QR bot example! I'll take a look at it. As for 'predefined links' for the text file, it's purely because I need a database of some sort. I've not thought of how to do it any other way as of yet. I can also use the github API, but the problem is that sometimes authors do not have a direct cia file download. I'll be using the 'database' as part of this repo or under a different one I can manage a bit easier (because universal links to that Github with easy-to-get URLs!)

**Comment by ksanislo** [comment]
You can load the full SMDH at once with "Range: bytes=(filelength-14016)-filelength" using the SMDH array as defined [in FBI here](https://github.com/Steveice10/FBI/blob/master/source/core/util.h)

That will give the graphics and everything with it. That's cleaner than just the English description part that I used for the QR bot.

If you're interested in hooking this with some kind of web API backend, I'd be willing to help put up a server to catalog what homebrew is available and where to find it so it can accept user submissions and you don't have to maintain the whole list of apps on your own.

**Comment by TurtleP** [comment]
That would be great! So what that would do is just find the latest of every cia file (if zipped, unzips it and looks for a cia extension perhaps) and places that into a database?

**Comment by ksanislo** [comment]
Yeah, I'm thinking something along the lines of just making an HTTP GET on a URL and have it kick back json of titleID, name, and location of the CIA file or .zip, perhaps a URL like https://hostname/filename.zip#/path/to/installable.cia in the archive, since there might be more than one cia in the same zip file.

I'd think that in the interest of avoiding any possible legal troubles if someone submitted a file that isn't open (we would still want to audit submitted URLs from time to time to avoid this anyway), it probably shouldn't host extracted data like the graphics, just links for where to find things. There's a performance penalty where the 3DS has to collect all the metadata, but it seems more "safe" from the hosting side of things. If its updated via a background thread and cached, it shouldn't be too much of a problem.

It would also be possible to add the same quirc based QR scanner to let people directly scan a URL in this app, and optionally ask to submit it to the API backend so new apps show up for everyone as soon as a user uses Flask to install them.

**Comment by TurtleP** [comment]
I've got a json parser in Flask already, though it's kind of difficult for me to understand how to use right now. We can use the json idea, but I'll have to figure it out haha. I'm so used to the one I use for my Lua stuff. I can definitely cache stuff if needed. Shouldn't be a problem. Right now it just grabs the icon image and text file from the repo for making sure the Application class works. If you get this set up soon I'll definitely try to get the json parsing to work properly. By the way, I do have my own domain but if you wish to do the whole API and such, fine by me (especially since I don't know how to make a web API)!. ;)

**Comment by ksanislo** [comment]
Which json parser are you using? I see the Makefile reference source/libs/json, but it seems that it's not checked into the repo. I tried a few of them when working with my 3ds projects, jansson seems to be the easiest and most reliable one that I came across, just for what it's worth.

**Comment by TurtleP** [comment]
Seems like I removed it. I'll check out the jansson one though.

**Comment by TurtleP** [comment]
I added the jansson json library. Oddly it just--works with everything. Thank god though. I'll try to do some json tests later. Let me know how your stuff is going on.

**Comment by ksanislo** [comment]
I've not had time to poke at any kind of an interface since I'm at work, but here's the homebrew.txt from the repo recreated in JSON as intended... do note the replacement of the unicode in the pokemon description, and the path to the cia inside the archives after the # character.

http://3ds.intherack.com/flask/list

This should be a stable URL to use, though we could optionally have flask.intherack.com or even pick up a whole new domain specifically for this if you're interested. That's all easy enough to change later.

**Comment by TurtleP** [comment]
Awesome. Not sure why you changed the Pokemon e to unicode. It'd be fine to do. The font I use supports it. I'd also rather if the fields 'ciaurl', 'desc', and 'dev' be just 'url', 'description', and 'author'. Sorry if that sounds nitpicky, but it's more legible to me and others,

**Comment by ksanislo** [comment]
Yeah, no problem with renaming entires, it's updated now. As far as escaping the é is mostly just because the python verify tool doesn't like extended ascii and prefers to turn it anything over 128 to Unicode escapes.

**Comment by TurtleP** [comment]
Seems like Flask doesn't want to download the list. Not sure if that's on my end or yours. I've tried resetting my internet settings, but that didn't fix it. Freeshop/FBI etc all work fine. Let me know if you can figure something out.

**Comment by ksanislo** [comment]
I'm not seeing requests in the server logs, so I think it's client related somehow. I'll poke at it more tomorrow when I get a minute, and see what I can find.

**Comment by ksanislo** [comment]
Alright, the bug is in [util.u at line 48](https://github.com/TurtleP/Flask/blob/master/source/util.cpp#L48), You can't use httpcGetDownloadSizeState() on dynamic or compressed content, since there's no size header when things are passed as Content-Encoding: chunked. You'll have to loop over calling download until it stops returning HTTPC_RESULTCODE_DOWNLOADPENDING, and resize the buffer up as you go.

**Comment by ksanislo** [comment]
So, I added titleid to the JSON returned, and you can add/update things to the DB by doing a POST with a body of: `{ "url": "http://3ds.intherack.com/files/QRWebLoader.cia" }`

I still need to add zip parsing for those files, and github updating automatically... and I'm still looking for a way to pull the version from the cia somewhere as well so I can add that.

**Comment by ksanislo** [comment]
The backend now updates github links automatically to their latest stable releases (every 5 minutes). Properly handling compressed files should be working soon, but I'm not fond of downloading and decompressing in order to scan inside things, sadly some common archive methods like RAR5 are a real pain in the ass and may not be workable without it.

I'll post it up on github somewhere shortly so you can poke through things if you'd like. I was also considering just saying fuck it and optionally providing the SMDH icons as base64 encoded in the json or something. Also, I'm going to rewrite the API call to let you specify which fields you want listed, which will make the backend more useful for generic projects that want a current list of homebrew or to verify titleIDs and stuff. I'll let you know before I change the live version.

**Comment by TurtleP** [comment]
Alright, I'm currently trying to sort out a crash (the commit is the current one where I try to do what you suggested) but until I fix that, I won't be able to really peek at that. I'll keep it in mind for when this clears up though!

**Comment by ksanislo** [comment]
Fwiw, the crash is @ line 56, size is uninitialized, I think you mean to use bufferSize instead there.

**Comment by TurtleP** [comment]
Buffer should have been mallocated. Ah well I'll fix that one. That's what writes the Json data.

**Comment by ksanislo** [comment]
There's a [pull request](https://github.com/TurtleP/Flask/pull/2)) to fix this and some other minor issues as well, in case you didn't see it.

**Comment by TurtleP** [comment]
Ah I didn't see it. Thanks! I'll continue looking into this.

**Comment by ksanislo** [comment]
The new API URL is https://api.titledb.com/v1/, You can do a basic GET on it for a simple list, or you can do a POST with a body JSON of { "action": "list", "fields": ["name", "description", "author", "titleid", "url"] } for the same data.... { "action": "list_fields" } will return what all is available for selection, since I'm still adding things.

And https://www.titledb.com is the main site, but the javascript for QR code generation and adding URLs directly isn't finished yet.

**Comment by TurtleP** [comment]
Alright, Flask is now able to load the json! I just need to figure out the header field stuff. If you know how that works, please let me know.

**Comment by ksanislo** [comment]
Which header field thing are you trying to use? I've probably got examples of it around...

**Comment by ksanislo** [comment]
So, as a side note, if you want to avoid parsing SMDH yourself entirely, I'll just index it all... less requests will make things much faster anyway... the graphics will be avaliable via a POST like:

 { "action": "list", "fields": ["name", "description", "author", "titleid", "url", "icon_large", "icon_small" ] }

They'll be base64 encoded binary data as extracted from the SMDH... Since they're somewhat larger, and in an awful format for anything but the 3DS's GPU, I don't expect them to ever be included in the basic GET list.

I'm working on getting them to import right now... Then the only Range: header you'll need to pull is that specific one for TitleID to make sure you're getting the same ID as the API gave you... Make sure to [swap endianness when converting from a byte array to a u64](https://github.com/ksanislo/devproject/blob/master/source/mega.cpp#L348) from that result first though!

**Comment by TurtleP** [comment]
All icons should be at the 48x48 size, so it's less of a hassle for both of us.

**Comment by ksanislo** [comment]
that's icon_large... you can include just that field if you only want the big one, both are now available to request now though (data is filling right now)

**Comment by ksanislo** [comment]
Oh... I just had an idea.... In the interest of saving some space since these are uncompressed images, do you want to implement zlib to decompress the base64 string, so we're only sending compressed data across the wire? It'll save on bandwidth if nothing else...

**Comment by TurtleP** [comment]
zlib is a requirement for it, so I have no choice to use it haha. Sure! I'll look into its usage.

**Comment by ksanislo** [comment]
Sweet... icon data is now run through zlib before being base64 encoded, the resulting data across the wire looks like it's around 1/3 the size on average.

**Comment by ksanislo** [comment]
One more little thing, since i'm looking at webserver logs... You should add a User-Agent header to every request you make. The content part is up to you, but Program/Version is pretty standard.

httpcAddRequestHeaderField(&context, (char*)"User-Agent", (char*)"Flask/1.0");

**Comment by TurtleP** [comment]
If it's fine, I'm going to do

httpcAddRequestHeaderField(&httpContext, (char *)"User-Agent/Flask", flaskVersion); 

This allows for me to just pass the version number and not have to worry to much about concating some strings.

**Comment by ksanislo** [comment]
That's a call to 3DS OS APIs that take two separate char pointers... the first part must be (char*)"User-Agent" alone, the second part will have to be built as a string with sprintf() or however you prefer, then be passed in as a (char*)

**Comment by TurtleP** [comment]
Oh, okay then. Didn't know. I'll fix that then.

**Comment by ksanislo** [comment]
I've added transparent proxying to be able to direct link to CIAs inside archives through titledb.com ... If you want to shortcut supporting a whole host of decompression you can have it install from GET http://api.titledb.com/v0/proxy/TitleIDinHEX using the titleid as returned by the API. You can't however use the Range: header to reposition, but I'm faking the Content-Size header so httpcGetDownloadSizeState() can still be used to show the full size. (FBI uses it while installing, so I had to make a hacky workaround)

I've added your Turtle: Invaders as an example if you want to go take a look at how it lists things currently.

**Comment by TurtleP** [comment]
Awesome. Sorry if I've not been updating this recently. Been busy doing other stuff, but I'll definitely try to do some more work this week.

**Comment by ksanislo** [comment]
FWIW, If you want any assistance with implementing the API side of this in flask, let me know and I'll poke at things. I've been leaving it alone since I don't know if you want anyone stepping on your toes or not while writing this thing.

**Comment by TurtleP** [comment]
I have no issue with any coding help. I'd like as much as I can get! I'm still confused about caching the data through a get request byte range *shrug*
